language: python
python:
  - "3.6"
services: 
  - postgresql
install:
  - pip install -r requirements.txt
  - pip install coveralls
script:
  - python manage.py test
  - coverage run --source='try/' manage.py test && coverage report

after_success:
  - coveralls
